# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f2eb22842607b48556673c278a85bba8eeaba287f5741c3058f8cc7e08fe3bca0cfa1cddae513b29e3f6136db931a6d2e5e8730014de6dd47c6e379edc4f365

test:
  secret_key_base: 96fd18517927cc1688d0640b4ebfcc90bbf68ac38cd02935f825e28771687fdd431fb391958806350bc5cceb3600621a42c863d02fb23af50f4115227eb6f433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
